# Generated by Django 4.1.3 on 2022-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=1000)),
                ('Numero_Cliente', models.BigIntegerField()),
                ('Nombre_Cliente', models.CharField(max_length=1000)),
                ('Fecha_Registro', models.DateField()),
                ('Apellido_Paterno', models.CharField(max_length=1000)),
                ('Apellido_Materno', models.CharField(max_length=1000)),
                ('Correo', models.CharField(max_length=1000)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Telefono', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codProducto', models.BigIntegerField()),
                ('Nombre_Producto', models.CharField(max_length=1000)),
                ('Proovedor', models.CharField(max_length=1000)),
                ('Categoria', models.CharField(max_length=1000)),
                ('Cantidad_por_Unidad', models.CharField(max_length=1000)),
                ('Valor_en_Peso', models.BigIntegerField()),
                ('Valor_en_Euro', models.FloatField()),
                ('Stock', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boleta', models.BigIntegerField()),
                ('Producto', models.BigIntegerField()),
                ('cantidad', models.BigIntegerField()),
                ('Venta_Bruto', models.BigIntegerField()),
                ('iva', models.FloatField()),
                ('Total_Venta', models.BigIntegerField()),
            ],
        ),
    ]
